### ISSUE TITLE
TA_ETW stopped working

### ISSUE THREAD

**Issue by Garthenag** [vector-sec/TA_ETW#4]
Hello,

we noticed TA_ETW using high memory (as described in previous issue) and admin restarted TA_ETW process. The memory usage has dropped but since then the app no longer pulls any logs. We have tried to reinstall agent, redeploy the app but it didn't help at all.

Is there an option to enable any logging on the app?

Regards,
Dawid

**Comment by vector-sec** [comment]
Closing this since it seems to be the same issue as #3
